//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedure_slip
    {
        public int mpd_id { get; set; }
        public int mp_code { get; set; }
        public Nullable<int> mr { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> mp_user_id { get; set; }
        public int mr_no { get; set; }
        public string First_name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Tel_no { get; set; }
        public string PRO_NAME { get; set; }
    }
}
