//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBl_CONS_FEE
    {
        public int fee_id { get; set; }
        public string fee_name { get; set; }
        public Nullable<int> fee_Fee { get; set; }
        public Nullable<int> fee_status { get; set; }
        public Nullable<int> fee_org { get; set; }
        public Nullable<int> fee_user { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
        public Nullable<int> fee_cons { get; set; }
    
        public virtual TBL_CONSULTANT TBL_CONSULTANT { get; set; }
    }
}
