//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MASTER_PRO_ENTRY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MASTER_PRO_ENTRY()
        {
            this.TBL_MPROC_DETAIL = new HashSet<TBL_MPROC_DETAIL>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_NAME { get; set; }
        public Nullable<int> PRO_CAT { get; set; }
        public Nullable<int> PRO_DISCOUNT { get; set; }
        public Nullable<int> PRO_AMOUNT { get; set; }
        public Nullable<int> PRO_PRICE { get; set; }
        public Nullable<int> PRO_EXPENSE { get; set; }
        public Nullable<int> PRO_TYPE { get; set; }
        public Nullable<int> PRO_HEAD { get; set; }
        public Nullable<int> PRO_ORG { get; set; }
        public Nullable<int> PRO_USER_ID { get; set; }
        public Nullable<System.DateTime> PRO_USER_DATE { get; set; }
        public string PRO_REFERANGE { get; set; }
        public string PRO_MEASUREMENT_UNIT { get; set; }
        public string PRO_SAMPLE { get; set; }
        public string PRO_SPECIMEN { get; set; }
        public Nullable<int> PRO_PANEL_TYPE { get; set; }
        public Nullable<int> PRO_CODE { get; set; }
        public Nullable<int> pro_shift { get; set; }
        public Nullable<int> PRO_CONS { get; set; }
        public Nullable<int> PRO_STATE { get; set; }
    
        public virtual TBL_PROCEDURE_CAT TBL_PROCEDURE_CAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MPROC_DETAIL> TBL_MPROC_DETAIL { get; set; }
    }
}
