//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MPROC_DETAIL
    {
        public int MPD_ID { get; set; }
        public Nullable<int> MP_CODE { get; set; }
        public Nullable<int> MR { get; set; }
        public Nullable<int> MPD_SAMPLE_ID { get; set; }
        public Nullable<int> MPD_SAMPLE_YN { get; set; }
        public string MPD_user_id { get; set; }
        public Nullable<int> MPD_USER_ORG { get; set; }
        public Nullable<System.DateTime> MPD_USER_DATE { get; set; }
        public string MPD_USER_NAME { get; set; }
        public Nullable<int> MPD_LAB_NO { get; set; }
        public Nullable<int> MPD_CAT { get; set; }
        public Nullable<int> MPD_PERFORMED { get; set; }
        public Nullable<int> MPD_DOCYN { get; set; }
        public Nullable<int> MPD_DOC_ID { get; set; }
        public Nullable<System.DateTime> MPD_DOC_DATE { get; set; }
        public string MPD_DOC_REMARKS { get; set; }
        public string MPD_REPORT { get; set; }
        public Nullable<int> MPD_SAMPLE_SATATUS { get; set; }
        public Nullable<int> MPD_REFER { get; set; }
        public Nullable<int> MPD_P_USER_ID { get; set; }
        public Nullable<System.DateTime> MPD_P_USERDATE { get; set; }
        public Nullable<int> MPD_TECH_ID { get; set; }
        public Nullable<System.DateTime> MPD_TECH_DATE { get; set; }
        public Nullable<int> MPD_order_id { get; set; }
        public Nullable<int> pro_id { get; set; }
        public Nullable<int> pro_amount { get; set; }
        public Nullable<int> pro_discount { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> MPD_QTY { get; set; }
        public Nullable<int> MPD_AMOUNT { get; set; }
    
        public virtual TBL_MASTER_PRO_ENTRY TBL_MASTER_PRO_ENTRY { get; set; }
        public virtual TBL_MASTER_PROCEDURE TBL_MASTER_PROCEDURE { get; set; }
    }
}
