//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAY_MAST
    {
        public int EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_FNAME { get; set; }
        public string EMP_MNAME { get; set; }
        public string SEX_MF { get; set; }
        public Nullable<int> EMP_CELL { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<int> ID_CARD { get; set; }
        public Nullable<int> EMP_PHONE { get; set; }
        public string EMP_EMAIL { get; set; }
        public string EMP_POSADD { get; set; }
        public string EMP_RELIGION { get; set; }
        public string EMP_SECT { get; set; }
        public string EMP_CAST { get; set; }
        public Nullable<System.DateTime> ID_EXP { get; set; }
        public string EMP_DESG { get; set; }
        public Nullable<int> EMP_PIC { get; set; }
        public Nullable<int> DEP_CODE { get; set; }
        public Nullable<System.DateTime> JOIN_DATE { get; set; }
        public Nullable<int> GROSS_SAL { get; set; }
        public Nullable<int> INCOME_TAX { get; set; }
        public Nullable<int> EMP_TAXNO { get; set; }
        public string EMP_ACCNO { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
        public string TERMINAT { get; set; }
        public Nullable<int> NET_SLRY { get; set; }
        public Nullable<int> INC_PAY { get; set; }
        public Nullable<int> CITY_CODE { get; set; }
        public Nullable<int> GROUP_CODE { get; set; }
        public Nullable<System.DateTime> RSG_DATE { get; set; }
        public string PAY_TYPE { get; set; }
        public string STATION { get; set; }
        public Nullable<int> EOBI { get; set; }
        public Nullable<int> CMP_CODE { get; set; }
        public Nullable<int> ETP_CODE { get; set; }
        public string AUTOTAX { get; set; }
        public Nullable<int> B_CODE { get; set; }
        public string APPYN { get; set; }
        public Nullable<int> SALCODE { get; set; }
        public string SOCIALYN { get; set; }
        public string EOBIYN { get; set; }
        public Nullable<int> USRID { get; set; }
        public string USTTY { get; set; }
        public Nullable<System.DateTime> SYS_DATE { get; set; }
        public Nullable<int> D_CODE { get; set; }
        public string EMPADD { get; set; }
        public Nullable<int> MESSDED { get; set; }
        public string OVERGB { get; set; }
        public Nullable<System.DateTime> SHIFT_DATE { get; set; }
        public Nullable<System.DateTime> SHTIME_I { get; set; }
        public Nullable<System.DateTime> SHTIME_O { get; set; }
        public string WEEK_OFF { get; set; }
        public string AUTOEXP { get; set; }
        public string CONYN { get; set; }
        public Nullable<int> SOCIALNO { get; set; }
        public Nullable<System.DateTime> CON_DATE { get; set; }
        public string BELONG { get; set; }
        public Nullable<int> EOBINO { get; set; }
        public string FACTYN { get; set; }
        public Nullable<System.DateTime> ALI_DATE { get; set; }
        public string EMP_REF { get; set; }
        public Nullable<int> CARDNO { get; set; }
        public Nullable<int> HEALTH { get; set; }
        public Nullable<int> FAX_NO { get; set; }
        public string EMNATI { get; set; }
        public string EMDDIS { get; set; }
        public string EMDPRO { get; set; }
        public string EMPTEH { get; set; }
        public string EMPDIS { get; set; }
        public string EMPPRO { get; set; }
        public string PREADD { get; set; }
        public string PRETEH { get; set; }
        public string PREDIS { get; set; }
        public string PREPRO { get; set; }
        public string FACTD { get; set; }
        public string POSDIS { get; set; }
        public string POSPRO { get; set; }
        public string EMMARI { get; set; }
        public string RSGTYP { get; set; }
        public string BANK_ACC { get; set; }
        public string E1 { get; set; }
        public string E2 { get; set; }
        public string E3 { get; set; }
        public string EX { get; set; }
        public Nullable<int> OLDCOD { get; set; }
        public string MACCOD { get; set; }
        public Nullable<int> TCODE { get; set; }
        public Nullable<int> NCODE { get; set; }
        public string PMDREG { get; set; }
        public Nullable<System.DateTime> PMDEXP { get; set; }
        public string FACREG { get; set; }
        public Nullable<System.DateTime> FACEXP { get; set; }
        public string SHTYPE { get; set; }
        public string EMPTIT { get; set; }
        public Nullable<int> REBATE { get; set; }
        public string ATT_YN { get; set; }
        public string PFNDYN { get; set; }
        public string FCTYPE { get; set; }
        public string INCHARGE { get; set; }
        public string PNCREG { get; set; }
        public Nullable<System.DateTime> PNCEXP { get; set; }
        public Nullable<System.DateTime> XADATE { get; set; }
        public Nullable<System.DateTime> XCDATE { get; set; }
        public Nullable<System.DateTime> XRDATE { get; set; }
        public Nullable<System.TimeSpan> PBTIME { get; set; }
        public Nullable<int> PBINCR { get; set; }
        public Nullable<int> JOINSAL { get; set; }
        public Nullable<int> RSGDAYS { get; set; }
        public Nullable<int> CVCODE { get; set; }
        public string EMPARE { get; set; }
        public Nullable<int> PKHORS { get; set; }
        public string SECURTY { get; set; }
        public string E_DI { get; set; }
        public string C_NAME { get; set; }
        public string D_NAME { get; set; }
        public string RWAL_FOUN { get; set; }
        public Nullable<int> S_CARD { get; set; }
        public Nullable<int> DOC { get; set; }
        public Nullable<int> APPL { get; set; }
        public Nullable<int> BIOT { get; set; }
        public Nullable<int> BANK { get; set; }
        public Nullable<int> FEE { get; set; }
        public Nullable<int> RSG_CODE { get; set; }
        public Nullable<int> DOCYN { get; set; }
        public string MED_ALLIED { get; set; }
        public Nullable<int> PRIVATE_PRACTICES { get; set; }
        public string SIGN { get; set; }
        public string HOSTELYN { get; set; }
        public Nullable<int> HOSTEL_CHARGES { get; set; }
        public string DAY_CAREYN { get; set; }
        public Nullable<int> DAYCARE_CHARGES { get; set; }
        public string DRIVE_LINCES { get; set; }
        public Nullable<System.DateTime> ENT_SYSDATE { get; set; }
        public string EOBI_MON { get; set; }
        public string EOBI_YEAR { get; set; }
        public Nullable<System.DateTime> EOBI_R_DATE { get; set; }
        public Nullable<int> DRYN { get; set; }
        public Nullable<int> SOCIAL_AMT { get; set; }
        public Nullable<int> EMP_TYPE { get; set; }
        public Nullable<int> EOBI_STATUS { get; set; }
    }
}
