//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MASTER_PROCEDURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MASTER_PROCEDURE()
        {
            this.TBL_MPROC_DETAIL = new HashSet<TBL_MPROC_DETAIL>();
        }
    
        public int MP_CODE { get; set; }
        public Nullable<System.DateTime> MP_DATE { get; set; }
        public Nullable<int> MR { get; set; }
        public Nullable<int> MP_NETAMOUNT { get; set; }
        public Nullable<int> MP_DISCOUNT_ID { get; set; }
        public Nullable<int> MP_DISCOUNT_PER { get; set; }
        public Nullable<int> MP_DIS_AMOUNT { get; set; }
        public Nullable<int> MP_GRANT_TOTAL { get; set; }
        public Nullable<int> MP_PIAD_AMOUNT { get; set; }
        public Nullable<int> MP_BLALANCE { get; set; }
        public Nullable<System.DateTime> MP_USER_dATE { get; set; }
        public Nullable<int> MP_USER_ORG { get; set; }
        public Nullable<int> MP_USER_ID { get; set; }
        public Nullable<int> MP_USER_MPCODE { get; set; }
        public Nullable<System.DateTime> MP_CLEAR_DATE { get; set; }
        public Nullable<int> MP_STATUS { get; set; }
        public Nullable<System.DateTime> MP_STATUS_DATE { get; set; }
        public Nullable<int> MP_STATUS_USER_ID { get; set; }
        public Nullable<System.DateTime> MP_STATUS_USER_DATE { get; set; }
        public Nullable<int> MP_PANEL { get; set; }
        public Nullable<int> MP_AMOUNT { get; set; }
        public Nullable<int> MP_PANEL_PAID { get; set; }
        public Nullable<int> MP_REM_PANEL { get; set; }
        public Nullable<int> MP_SHIFT { get; set; }
        public Nullable<int> MP_SHIFT_ID { get; set; }
        public Nullable<int> MP_CONS { get; set; }
        public Nullable<int> MP_SHARE_AMOUNT { get; set; }
        public Nullable<int> MP_SHARE_CONS { get; set; }
        public Nullable<int> MP_SHARED_PAID_STATUS { get; set; }
        public Nullable<System.DateTime> MP_SHARED_DATE { get; set; }
        public Nullable<int> MP_SHARED_USER_ID { get; set; }
    
        public virtual TBL_R_PATIENT TBL_R_PATIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MPROC_DETAIL> TBL_MPROC_DETAIL { get; set; }
    }
}
