//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PROCEDURE_CAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PROCEDURE_CAT()
        {
            this.TBL_MASTER_PRO_ENTRY = new HashSet<TBL_MASTER_PRO_ENTRY>();
        }
    
        public int pc_id { get; set; }
        public string pc_name { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> user_org { get; set; }
        public Nullable<System.DateTime> user_Date { get; set; }
        public Nullable<int> dept { get; set; }
        public Nullable<int> org_id { get; set; }
    
        public virtual TBL_R_DEPT TBL_R_DEPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MASTER_PRO_ENTRY> TBL_MASTER_PRO_ENTRY { get; set; }
    }
}
