//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_LAB
    {
        public int TEST_ID { get; set; }
        public int MR_NO { get; set; }
        public Nullable<int> AGE { get; set; }
        public string FIRST_NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string GENDER { get; set; }
        public string TEL_NO { get; set; }
        public Nullable<int> MP_GRANT_TOTAL { get; set; }
        public Nullable<System.DateTime> MP_USER_DATE { get; set; }
        public Nullable<int> MP_USER_ID { get; set; }
        public Nullable<int> MP_CONS { get; set; }
        public string MPD_USER_ID { get; set; }
        public Nullable<int> MPD_SAMPLE_ID { get; set; }
        public Nullable<int> MPD_SAMPLE_YN { get; set; }
        public string PRO_NAME { get; set; }
        public Nullable<int> PRO_CAT { get; set; }
        public int PRO_ID { get; set; }
    }
}
